# 追加した規約ファイル読込
require:
  - rubocop-rails # Railsに関わる構文規則チェック
  - rubocop-performance # パフォーマンスに関わる構文規則チェック

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.6
  # 除外
  Exclude:
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - Gemfile
    - 'app/helpers/devise_helper.rb'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# メソッド15行まで許可
MethodLength:
  CountComments: false
  Max: 15

# ガード区、5行まで許可
Style/GuardClause:
  MinBodyLength: 5
