version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          - BUNDLER_VERSION: 2.1.4
          - RAILS_ENV: 'test'
          # - POSTGRES_USER: postgres
          # - RAILS_ENV: test
          # - DATABASE_PASSWORD: postgres
      - image: circleci/postgres
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_DB: yatta_app_test
          - POSTGRES_HOST_AUTH_METHOD: trust
          - POSTGRES_PASSWORD: postgres
    working_directory: ~/yatta_app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      # - run: mv ./config/database.ci.yml ./config/database.yml
      # - run: mv ./spec/rails_helper.ci.rb ./spec/rails_helper.rb
      - run: gem install bundler:2.1.4
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      # - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: mv ./config/database.ci.yml ./config/database.yml
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Rspec
          command: bundle exec rspec

#   deploy:
#     docker:
#       - image: circleci/ruby:2.6.5-node-browsers-legacy
#     steps:
#       - checkout
#       - ruby/install-deps
#       - add_ssh_keys:
#           fingerprints: FINGERPRINTS
#       - deploy:
#           name: Capistrano deploy
#           command: bundle exec cap production deploy

# workflows:
#   version: 2
#   build_accept_deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master